### ISSUE TITLE
demo_generator shortage

### ISSUE THREAD

**Issue by pengtianyue** [pengtianyue/Solvay_test#4]
1. It doesn't identify state attributes in parent states (that include substates) now
2. OPC_Connect.client.write(PV,SP): the SP can only be a number or string of number now. i.e. "20", "18.66", etc
3. is_active flag of state is not useful here.

These should be repaired later.

**Comment by mekcrab** [comment]
All of these issues should be handle by AttributeType.Attribute_Base subclasses.

**Comment by mekcrab** [comment]
Superstates attribute will be include by boolean AND to substate attributes in a flattened graph used by the test solver.

**Comment by mekcrab** [comment]
Updates listed here either already fixed or tracked in issues #9 and #23. Closing issue.
