### ISSUE TITLE
Transition deadbands

### ISSUE THREAD

**Issue by mekcrab** [pengtianyue/Solvay_test#6]
Transitions should be “stuck” and wait within a deadband.

==> Should be put in the Attribute class as discussed. See AttributeTypes.py for class skeletons.

**Comment by mekcrab** [comment]
A given AttributeType should verify it's own deadband. This can be based on percentage of PV or a default value (ex. 0.01) to prevent stuck transitions from floating point roundoff errors.

**Comment by pengtianyue** [comment]
default deadband as 0 initially. Set deadband (in simulation) if needed.

**Comment by mekcrab** [comment]
Added this functionality in attribute_types branch under Compare attribute. Issue closed.
