### ISSUE TITLE
Modes - ACTUAL vs TARGET

### ISSUE THREAD

**Issue by mekcrab** [pengtianyue/Solvay_test#7]
The confirm for Actions(state_attrs) should be modified to the correct parameter, i.e. MODE.ACTUAL for MODE.TARGET 

==>ModeAttribute class should cover this

**Comment by mekcrab** [comment]
We will need a special AttributeType for modes. Setting a mode writes to MODE.TARGET, checking a mode will refer to MODE.ACTUAL.

What to do about REQ_MODE?

**Comment by pengtianyue** [comment]
We can just use MODE.TARGET and MODE.ACTUAL. Writing values into REQ_MODE.TARGET just gives a modelock based on the MODE.TARGET, we don't need that.

**Comment by mekcrab** [comment]
Added this functionality as ModeAttribute in attribute_types branch. Issue closed.
